spring:
  datasource:
    url: 'jdbc:mysql://localhost:3307/schema_shop'
    username: root
    password: P@ssw0rdS
  data:
    rest:
      base-path: /api
---
spring:
  profiles: dev
---
spring:
  profiles: prod
